### ISSUE TITLE
Node Backend: Unable to connect to the database

### ISSUE THREAD

**Issue by Fasust** [devonfw/my-thai-star#314]
Hey Guy,
I have a small problem starting the NodeJs version of the back-end:

### Expected behavior
I want to run the back-end implemented in NodeJs locally on my machine. I installed the dependencies using yarn and then tried all the start up versions defied in the package.json.

```json
"start": "ts-node -r tsconfig-paths/register src/main.ts",
"start:dev": "tsc-watch -p tsconfig.build.json --onSuccess \"node dist/main.js\"",
"start:debug": "tsc-watch -p tsconfig.build.json --onSuccess \"node --inspect-brk dist/main.js\"",
 "start:prod": "node dist/main.js"
```

### Actual behavior
All of them, however, throw the same error:

```bash
> node@1.0.0 start:dev D:\Documents\Programmieren\my-thai-star\node
> tsc-watch -p tsconfig.build.json --onSuccess "node dist/main.js"


5:00:26 PM - Starting compilation in watch mode...


5:00:34 PM - Found 0 errors. Watching for file changes.
[Nest] 20964   - 11/24/2019, 5:00 PM   [NestFactory] Starting Nest application...
[Nest] 20964   - 11/24/2019, 5:00 PM   [InstanceLoader] AppModule dependencies initialized
[Nest] 20964   - 11/24/2019, 5:00 PM   [InstanceLoader] ConfigurationModule dependencies initialized
[Nest] 20964   - 11/24/2019, 5:00 PM   [InstanceLoader] TypeOrmModule dependencies initialized      
[Nest] 20964   - 11/24/2019, 5:00 PM   [InstanceLoader] PassportModule dependencies initialized
[Nest] 20964   - 11/24/2019, 5:00 PM   [InstanceLoader] HttpModule dependencies initialized    
[Nest] 20964   - 11/24/2019, 5:00 PM   [InstanceLoader] TerminusModule dependencies initialized
[Nest] 20964   - 11/24/2019, 5:00 PM   [InstanceLoader] JwtModule dependencies initialized     
[Nest] 20964   - 11/24/2019, 5:00 PM   [InstanceLoader] MailerModule dependencies initialized
[Nest] 20964   - 11/24/2019, 5:00 PM   [InstanceLoader] TerminusModule dependencies initialized
[Nest] 19728   - 11/24/2019, 4:45 PM   [TypeOrmModule] Unable to connect to the database. Retrying (1)... +2013ms
Error: connect ECONNREFUSED 127.0.0.1:3306
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
    --------------------
    at Protocol._enqueue (D:\Documents\Programmieren\my-thai-star\node\node_modules\mysql\lib\protocol\Protocol.js:144:48)
    at Protocol.handshake (D:\Documents\Programmieren\my-thai-star\node\node_modules\mysql\lib\protocol\Protocol.js:51:23)
    at PoolConnection.connect (D:\Documents\Programmieren\my-thai-star\node\node_modules\mysql\lib\Connection.js:119:18)
    at Pool.getConnection (D:\Documents\Programmieren\my-thai-star\node\node_modules\mysql\lib\Pool.js:48:16)
    at D:\Documents\Programmieren\my-thai-star\node\node_modules\typeorm\driver\mysql\MysqlDriver.js:764:18
    at new Promise (<anonymous>)
    at MysqlDriver.createPool (D:\Documents\Programmieren\my-thai-star\node\node_modules\typeorm\driver\mysql\MysqlDriver.js:761:16)    at MysqlDriver.<anonymous> (D:\Documents\Programmieren\my-thai-star\node\node_modules\typeorm\driver\mysql\MysqlDriver.js:274:51)
    at step (D:\Documents\Programmieren\my-thai-star\node\node_modules\tslib\tslib.js:136:27)
    at Object.next (D:\Documents\Programmieren\my-thai-star\node\node_modules\tslib\tslib.js:117:57)
```

If I edit the configurations to instead use the sqlite data base I get a similar error:
```bash
...
[Nest] 20772   - 11/24/2019, 4:53 PM   [TypeOrmModule] Unable to connect to the database. Retrying (1)... +192ms
DataTypeNotSupportedError: Data type "timestamp" in "InvitedGuest.modificationDate" is not supported by "sqlite" database.
    at new DataTypeNotSupportedError (D:\Documents\Programmieren\my-thai-star\node\node_modules\typeorm\error\DataTypeNotSupportedError.js:7:28)
    at D:\Documents\Programmieren\my-thai-star\node\node_modules\typeorm\metadata-builder\EntityMetadataValidator.js:73:27
    at Array.forEach (<anonymous>)
    at EntityMetadataValidator.validate (D:\Documents\Programmieren\my-thai-star\node\node_modules\typeorm\metadata-builder\EntityMetadataValidator.js:70:36)
    at D:\Documents\Programmieren\my-thai-star\node\node_modules\typeorm\metadata-builder\EntityMetadataValidator.js:41:74
    at Array.forEach (<anonymous>)
    at EntityMetadataValidator.validateMany (D:\Documents\Programmieren\my-thai-star\node\node_modules\typeorm\metadata-builder\EntityMetadataValidator.js:41:25)
    at Connection.buildMetadatas (D:\Documents\Programmieren\my-thai-star\node\node_modules\typeorm\connection\Connection.js:500:33)    at Connection.<anonymous> (D:\Documents\Programmieren\my-thai-star\node\node_modules\typeorm\connection\Connection.js:126:30)   
    at step (D:\Documents\Programmieren\my-thai-star\node\node_modules\tslib\tslib.js:136:27)
```

### Comments/Hints:
Do I need to start the database manually / is it not automatically started with the npm script?

### Affected version:

* OS: Windows
-------
Thanks in advance :)

Regards,
Sebastian

**Comment by markusschuh** [comment]
AFAIK there is a deployment configuration for mariadb within the provided docker-compose.yml. 
So if you have a docker environment you can just try  with `docker-compose`.

If you want to use Maria DB also for local development you may need to install / start Maria DB as standalone service on your own, so the DB service listens on localhost:3306 and provides a database and authentication matching the configuration. This isn't too complicated to achieve based on the existing windows installers available at https://downloads.mariadb.org/ - try it.
Or you use a mariadb deployed within a docker environment from processes running on your windows host. Should work also but may be a bit more advanced to setup.

Your issue with SQLite is a quite different one and should be handled in an own issue. It looks to me, as if first SQLite was introduced in the configuration - and later the data model had been updated to also include elements of data type "timestamp".  This datatype is not supported by SQLite - so either another in-memory database need to be introduced in the setup - or the data model need to be optimized to also support SQLite. (date/time values would need to be stored as number data types for SQLite and the conversion to datetime need to be handled via functions)

**Comment by Fasust** [comment]
Thanks for the help @markusschuh ,

> On a side note, I'm trying to run the mts back-end locally and expose it's rest end-point through my localhost address. I am currently working on a Flutter Front-end for mts and want to test it against one of the back-end implementations.

I tried using the docker-compose file in the node sub-folder and got a very similar error message from the _mts\_node_ container, it's unable to connect to the database:

```bash
Starting node_maildev_1         ... done
Starting mts_node               ... done
Starting mts_angular_node       ... done
Starting node_mariadb_1         ... done
Starting mts_reverse_proxy_node ... done
Attaching to mts_reverse_proxy_node, node_maildev_1, mts_node, mts_angular_node, node_mariadb_1
maildev_1        | MailDev webapp running at http://0.0.0.0:80
mts_node         |
mts_node         | > node@1.0.0 start:prod /usr/src/app       
mts_node         | > node dist/main.js
mts_node         |
maildev_1        | MailDev SMTP Server running at 0.0.0.0:25
mariadb_1        | 2019-11-27 13:42:20 139811858532288 [Note] mysqld (mysqld 10.1.16-MariaDB-1~jessie) starting as process 1 ...
mariadb_1        | 2019-11-27 13:42:20 139811858532288 [Note] InnoDB: Using mutexes to ref count buffer pool pages
mariadb_1        | 2019-11-27 13:42:20 139811858532288 [Note] InnoDB: The InnoDB memory heap is disabled
mariadb_1        | 2019-11-27 13:42:20 139811858532288 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
mariadb_1        | 2019-11-27 13:42:20 139811858532288 [Note] InnoDB: Memory barrier is not used
mariadb_1        | 2019-11-27 13:42:20 139811858532288 [Note] InnoDB: Compressed tables use zlib 1.2.8
mariadb_1        | 2019-11-27 13:42:20 139811858532288 [Note] InnoDB: Using Linux native AIO
mariadb_1        | 2019-11-27 13:42:20 139811858532288 [Note] InnoDB: Using SSE crc32 instructions
mariadb_1        | 2019-11-27 13:42:20 139811858532288 [Note] InnoDB: Initializing buffer pool, size = 256.0M
mariadb_1        | 2019-11-27 13:42:20 139811858532288 [Note] InnoDB: Completed initialization of buffer pool
mariadb_1        | 2019-11-27 13:42:20 139811858532288 [Note] InnoDB: Highest supported file format is Barracuda.
mariadb_1        | 2019-11-27 13:42:20 139811858532288 [Note] InnoDB: 128 rollback segment(s) are active.
mariadb_1        | 2019-11-27 13:42:20 139811858532288 [Note] InnoDB: Waiting for purge to start
mariadb_1        | 2019-11-27 13:42:20 139811858532288 [Note] InnoDB:  Percona XtraDB (http://www.percona.com) 5.6.30-76.3 started; log sequence number 1616859
mariadb_1        | 2019-11-27 13:42:20 139811079816960 [Note] InnoDB: Dumping buffer pool(s) not yet started
mariadb_1        | 2019-11-27 13:42:20 139811858532288 [Note] Plugin 'FEEDBACK' is disabled.
mariadb_1        | 2019-11-27 13:42:20 139811858532288 [Note] Server socket created on IP: '::'.
mariadb_1        | 2019-11-27 13:42:20 139811858532288 [Warning] 'proxies_priv' entry '@% root@b9ae1219d5e2' ignored in --skip-name-resolve mode.
mariadb_1        | 2019-11-27 13:42:20 139811858532288 [Note] mysqld: ready for connections.
mariadb_1        | Version: '10.1.16-MariaDB-1~jessie'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  mariadb.org 
binary distribution
mts_node         | [Nest] 18   - 11/27/2019, 1:42 PM   [NestFactory] Starting Nest application...
mts_node         | [Nest] 18   - 11/27/2019, 1:42 PM   [InstanceLoader] AppModule dependencies initialized
mts_node         | [Nest] 18   - 11/27/2019, 1:42 PM   [InstanceLoader] ConfigurationModule dependencies initialized
mts_node         | [Nest] 18   - 11/27/2019, 1:42 PM   [InstanceLoader] TypeOrmModule dependencies initialized
mts_node         | [Nest] 18   - 11/27/2019, 1:42 PM   [InstanceLoader] PassportModule dependencies initialized
mts_node         | [Nest] 18   - 11/27/2019, 1:42 PM   [InstanceLoader] HttpModule dependencies initialized
mts_node         | [Nest] 18   - 11/27/2019, 1:42 PM   [InstanceLoader] TerminusModule dependencies initialized
mts_node         | [Nest] 18   - 11/27/2019, 1:42 PM   [InstanceLoader] JwtModule dependencies initialized
mts_node         | [Nest] 18   - 11/27/2019, 1:42 PM   [InstanceLoader] MailerModule dependencies initialized
mts_node         | [Nest] 18   - 11/27/2019, 1:42 PM   [InstanceLoader] TerminusModule dependencies initialized
mts_node         | [Nest] 18   - 11/27/2019, 1:42 PM   [TypeOrmModule] Unable to connect to the database. Retrying (1)... +1704ms
mts_node         | Error: getaddrinfo ENOTFOUND de-mucdevondepl01
mts_node         |     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:60:26)
mts_node         |     --------------------
mts_node         |     at Protocol._enqueue (/usr/src/app/node_modules/mysql/lib/protocol/Protocol.js:144:48)
mts_node         |     at Protocol.handshake (/usr/src/app/node_modules/mysql/lib/protocol/Protocol.js:51:23)
mts_node         |     at PoolConnection.connect (/usr/src/app/node_modules/mysql/lib/Connection.js:119:18)
mts_node         |     at Pool.getConnection (/usr/src/app/node_modules/mysql/lib/Pool.js:48:16)
mts_node         |     at /usr/src/app/node_modules/typeorm/driver/mysql/MysqlDriver.js:764:18
mts_node         |     at new Promise (<anonymous>)
mts_node         |     at MysqlDriver.createPool (/usr/src/app/node_modules/typeorm/driver/mysql/MysqlDriver.js:761:16)
mts_node         |     at MysqlDriver.<anonymous> (/usr/src/app/node_modules/typeorm/driver/mysql/MysqlDriver.js:274:51)
mts_node         |     at step (/usr/src/app/node_modules/tslib/tslib.js:136:27)
mts_node         |     at Object.next (/usr/src/app/node_modules/tslib/tslib.js:117:57)
mts_node         | [Nest] 18   - 11/27/2019, 1:42 PM   [TypeOrmModule] Unable to connect to the database. Retrying (2)... +4778ms
```

I the tried installing MariaDB locally. I set it up with the configurations specified in the _config/production.cs_. The node service is now able to make a connection but unable to fill the database. It tries transferring data but ends on this error:

````bash
[Nest] 5228   - 11/27/2019, 3:48 PM   [TypeOrmModule] Unable to connect to the database. Retrying (9)... +11296ms
QueryFailedError: ER_DUP_ENTRY: Duplicate entry '1' for key 'PRIMARY'
    at new QueryFailedError (D:\Documents\Programmieren\my-thai-star\node\src\error\QueryFailedError.ts:9:9)
    at Query.<anonymous> (D:\Documents\Programmieren\my-thai-star\node\src\driver\mysql\MysqlQueryRunner.ts:166:37)    
    at Query.<anonymous> (D:\Documents\Programmieren\my-thai-star\node\node_modules\mysql\lib\Connection.js:525:10)    
    at Query._callback (D:\Documents\Programmieren\my-thai-star\node\node_modules\mysql\lib\Connection.js:491:16)      
    at Query.Sequence.end (D:\Documents\Programmieren\my-thai-star\node\node_modules\mysql\lib\protocol\sequences\Sequence.js:83:24)
    at Query.ErrorPacket (D:\Documents\Programmieren\my-thai-star\node\node_modules\mysql\lib\protocol\sequences\Query.js:90:8)
    at Protocol._parsePacket (D:\Documents\Programmieren\my-thai-star\node\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (D:\Documents\Programmieren\my-thai-star\node\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (D:\Documents\Programmieren\my-thai-star\node\node_modules\mysql\lib\protocol\Parser.js:43:10)     
    at Protocol.write (D:\Documents\Programmieren\my-thai-star\node\node_modules\mysql\lib\protocol\Protocol.js:38:16) 
[Nest] 5228   - 11/27/2019, 3:48 PM   [ExceptionHandler] ER_DUP_ENTRY: Duplicate entry '1' for key 'PRIMARY' +10ms     
QueryFailedError: ER_DUP_ENTRY: Duplicate entry '1' for key 'PRIMARY'
    at new QueryFailedError (D:\Documents\Programmieren\my-thai-star\node\src\error\QueryFailedError.ts:9:9)
    at Query.<anonymous> (D:\Documents\Programmieren\my-thai-star\node\src\driver\mysql\MysqlQueryRunner.ts:166:37)    
    at Query.<anonymous> (D:\Documents\Programmieren\my-thai-star\node\node_modules\mysql\lib\Connection.js:525:10)    
    at Query._callback (D:\Documents\Programmieren\my-thai-star\node\node_modules\mysql\lib\Connection.js:491:16)      
    at Query.Sequence.end (D:\Documents\Programmieren\my-thai-star\node\node_modules\mysql\lib\protocol\sequences\Sequence.js:83:24)
    at Query.ErrorPacket (D:\Documents\Programmieren\my-thai-star\node\node_modules\mysql\lib\protocol\sequences\Query.js:90:8)
    at Protocol._parsePacket (D:\Documents\Programmieren\my-thai-star\node\node_modules\mysql\lib\protocol\Protocol.js:291:23)
291:23)
    at Parser._parsePacket (D:\Documents\Programmieren\my-thai-star\node\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (D:\Documents\Programmieren\my-thai-star\node\node_modules\mysql\lib\protocol\Parser.js:43:10)     
    at Protocol.write (D:\Documents\Programmieren\my-thai-star\node\node_modules\mysql\lib\protocol\Protocol.js:38:16) 
[Nest] 5228   - 11/27/2019, 3:48 PM   [ExceptionHandler] ER_DUP_ENTRY: Duplicate entry '1' for key 'PRIMARY' +10ms     
QueryFailedError: ER_DUP_ENTRY: Duplicate entry '1' for key 'PRIMARY'
    at new QueryFailedError (D:\Documents\Programmieren\my-thai-star\node\src\error\QueryFailedError.ts:9:9)
    at Query.<anonymous> (D:\Documents\Programmieren\my-thai-star\node\src\driver\mysql\MysqlQueryRunner.ts:166:37)    
    at Query.<anonymous> (D:\Documents\Programmieren\my-thai-star\node\node_modules\mysql\lib\Connection.js:525:10)    
    at Query._callback (D:\Documents\Programmieren\my-thai-star\node\node_modules\mysql\lib\Connection.js:491:16)      
    at Query.Sequence.end (D:\Documents\Programmieren\my-thai-star\node\node_modules\mysql\lib\protocol\sequences\Sequence.js:83:24)
    at Query.ErrorPacket (D:\Documents\Programmieren\my-thai-star\node\node_modules\mysql\lib\protocol\sequences\Query.js:90:8)
    at Protocol._parsePacket (D:\Documents\Programmieren\my-thai-star\node\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (D:\Documents\Programmieren\my-thai-star\node\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (D:\Documents\Programmieren\my-thai-star\node\node_modules\mysql\lib\protocol\Parser.js:43:10)     
    at Protocol.write (D:\Documents\Programmieren\my-thai-star\node\node_modules\mysql\lib\protocol\Protocol.js:38:16) 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node@1.0.0 start: `ts-node -r tsconfig-paths/register src/main.ts "dev"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\sebas\AppData\Roaming\npm-cache\_logs\2019-11-27T14_48_27_112Z-debug.log
````

I suspect it is not properly incrementing the primary key for each entry. The MariaDB looks like this after the start Script exits:

![image](https://user-images.githubusercontent.com/30209993/69733766-2a0ec400-112e-11ea-9d0a-b709ea3a4686.png)

Regards,
Sebastian

**Comment by markusschuh** [comment]
I confirm - the `docker-compose up -d` on my Windows runs into same error. Looks to me, as if the code within repository can only run on this - internally existing - server. Needs more investigation - but since there is a Db container started, it should be possible to use it - somehow,

**Comment by markusschuh** [comment]
Some steps forward:

The docker-compose,yml contains the `mariadb` as a container, which db port is exposed to the host and then referenced - from within the `src/config/production.ts` as a DB on this external host port. This may be the best way for the demo server for some reason - but typically the network path to the db within a docker-compose created environment could just be the direct network path **within** the created docker network.

So in a - not yet existing within the repository - `NODE_ENV=docker`, which reads the configuration from `src/config/docker.ts` the host for the DB were just the name of the DB service within the `docker-compose.yml` - which is configured as  `mariadb`.

Unfortunately there is still something missing. It is no longer a name resolution error - `getaddrinfo ENOTFOUND` - the error message now is

```
mts_node         | [Nest] 18   - 11/27/2019, 9:04 PM   [TypeOrmModule] Unable to connect to the database. Retrying (1)... +13ms
mts_node         | Error: connect ECONNREFUSED 172.18.0.5:3306
```

I'd say it is no longer a network connectivity error. Name is resolvable and port is open:

```
docker exec -it mts_node bash -c "timeout 5 bash -c '</dev/tcp/mariadb/3306'; echo $?"
0
```

And I now also realize, that mts tables have been created within the test database, so the database connection errors in docker logs just seem to be temporarily ones. I ignore them for the moment.

```
docker exec -it node_mariadb_1 mysql -h mariadb -u test -ptest test -e "show tables"
+--------------------------+
| Tables_in_test           |
+--------------------------+
| BinaryObject             |
| Booking                  |
| Category                 |
| Dish                     |
| DishCategory             |
| DishIngredient           |
| Image                    |
| Ingredient               |
| InvitedGuest             |
| OrderDishExtraIngredient |
| OrderLine                |
| Orders                   |
| RevInfo                  |
| Tables                   |
| UserFavourite            |
| UserRole                 |
| Users                    |
| migrations               |
+--------------------------+
```

Access via the IP of my docker  ( from `docker-machine ip` ) on
```
http://192.168.99.101:8091/restaurant
```

seems to have now a working connectivity with the backend API. For example, I can book a table and see the mail then at

```
http://192.168.99.101:8092/
```

I have not yet prepared a PR for the needed changes, sorry.

**Comment by Fasust** [comment]
Thank you for your effort @markusschuh. 
I'm looking forward to the pull-request.

**Comment by markusschuh** [comment]
It might be I need a while for a "good" PR. Quick workaround is just:  replace the db hostname within the src\config\production.ts  --  that is " .... database:  .... host: 'de-...'  --  with 'mariadb'. That's it.

The PR that I have in mind should just do this change - together with some other tuning - in a way, that the original use for the "production.ts" environment  is not disturbed.

**Comment by Fasust** [comment]
Yes, thanks @markusschuh.
That did the trick.

**Comment by dario-rodriguez** [comment]
Hello @Fasust @markusschuh , 
This is my fault. For local development, in order to be align with the java backend, the database must be a in memory database. As TypeORM do not support H2 I use sqlite.

The docker-compose should start a production environment but there are also some problems: the production configuration points to a machine instead to the mariadb container.

I already solve the problems and will create a PR soon.

**Comment by dario-rodriguez** [comment]
Hello @Fasust ,
I already created the PR #317 , can you check that now everything is working fine ? 
Now the command `yarn start:dev` and `docker-compose up` should work.

**Comment by Fasust** [comment]
Hey @dario-rodriguez ,

Yes I am no longer getting the error in your version. Thank you 👍

**Comment by baumeister25** [comment]
The error seems to be solved looking at the comment history. 
Closing this issue
