### ISSUE TITLE
Cannot register an user

### ISSUE THREAD

**Issue by other019** [devonfw/my-thai-star#343]
### Expected behavior

As a user, I want register an account so that I can book a table.

### Actual behavior
App shows red notificaton ballon with 
`Http failure response for http://localhost:8081/api/login: 401 OK`
in logs
```
mts_java         | [D: 2020-06-01 14:19:22,600] [P: INFO ] [C: ] [T: http-nio-8081-exec-1] [L: org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/mythaistar]] - [M: Initializing Spring DispatcherServlet 'dispatcherServlet']  
mts_java         | [D: 2020-06-01 14:19:22,601] [P: INFO ] [C: ] [T: http-nio-8081-exec-1] [L: org.springframework.web.servlet.DispatcherServlet] - [M: Initializing Servlet 'dispatcherServlet']  
mts_java         | [D: 2020-06-01 14:19:22,619] [P: INFO ] [C: ] [T: http-nio-8081-exec-1] [L: org.springframework.web.servlet.DispatcherServlet] - [M: Completed initialization in 18 ms]  
mts_java         | [D: 2020-06-01 14:19:22,684] [P: DEBUG] [C: ] [T: HikariPool-1 housekeeper] [L: com.zaxxer.hikari.pool.HikariPool] - [M: HikariPool-1 - Pool stats (total=10, active=0, idle=10, waiting=0)]  
mts_java         | [D: 2020-06-01 14:19:22,686] [P: DEBUG] [C: ] [T: http-nio-8081-exec-1] [L: com.devonfw.application.mtsj.general.common.base.JWTLoginFilter] - [M: Request is to process authentication]  
mts_java         | [D: 2020-06-01 14:19:22,859] [P: DEBUG] [C: ] [T: http-nio-8081-exec-1] [L: org.hibernate.SQL] - [M: select userentity0_.id as id1_19_, userentity0_.modificationCounter as modifica2_19_, userentity0_.email as email3_19_, userentity0_.password as password4_19_, userentity0_.secret as secret5_19_, userentity0_.twoFactorStatus as twofacto6_19_, userentity0_.idRole as idrole8_19_, userentity0_.username as username7_19_ from User userentity0_ where userentity0_.username=?]  
mts_java         | [D: 2020-06-01 14:19:22,868] [P: TRACE] [C: ] [T: http-nio-8081-exec-1] [L: org.hibernate.type.descriptor.sql.BasicBinder] - [M: binding parameter [1] as [VARCHAR] - [null]]  
mts_java         | [D: 2020-06-01 14:19:22,892] [P: WARN ] [C: ] [T: http-nio-8081-exec-1] [L: com.devonfw.application.mtsj.general.common.impl.security.BaseUserDetailsService] - [M: Failed to get user null.]  
mts_java         | org.springframework.security.core.userdetails.UsernameNotFoundException: Authentication failed.
mts_java         | 	at com.devonfw.application.mtsj.general.common.impl.security.BaseUserDetailsService.retrievePrincipal(BaseUserDetailsService.java:166)
mts_java         | 	at com.devonfw.application.mtsj.general.common.impl.security.BaseUserDetailsService.loadUserByUsername(BaseUserDetailsService.java:85)
mts_java         | 	at com.devonfw.application.mtsj.general.common.base.JWTLoginFilter.attemptAuthentication(JWTLoginFilter.java:53)
mts_java         | 	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:212)
mts_java         | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
mts_java         | 	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:200)
mts_java         | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
mts_java         | 	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:116)
mts_java         | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
mts_java         | 	at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:92)
mts_java         | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
mts_java         | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
mts_java         | 	at org.springframework.security.web.header.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:92)
mts_java         | 	at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:77)
mts_java         | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
mts_java         | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
mts_java         | 	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
mts_java         | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
mts_java         | 	at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56)
mts_java         | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
mts_java         | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
mts_java         | 	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:215)
mts_java         | 	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:178)
mts_java         | 	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:358)
mts_java         | 	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:271)
mts_java         | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
mts_java         | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
mts_java         | 	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
mts_java         | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
mts_java         | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
mts_java         | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
mts_java         | 	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
mts_java         | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
mts_java         | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
mts_java         | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
mts_java         | 	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:109)
mts_java         | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
mts_java         | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
mts_java         | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
mts_java         | 	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
mts_java         | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
mts_java         | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
mts_java         | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
mts_java         | 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
mts_java         | 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
mts_java         | 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
mts_java         | 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
mts_java         | 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
mts_java         | 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
mts_java         | 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
mts_java         | 	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373)
mts_java         | 	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
mts_java         | 	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
mts_java         | 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1594)
mts_java         | 	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
mts_java         | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
mts_java         | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
mts_java         | 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
mts_java         | 	at java.base/java.lang.Thread.run(Unknown Source)
mts_java         | Caused by: java.lang.NullPointerException: null
mts_java         | 	at com.devonfw.application.mtsj.usermanagement.logic.impl.UsermanagementImpl.findUserProfileByLogin(UsermanagementImpl.java:203)
mts_java         | 	at com.devonfw.application.mtsj.usermanagement.logic.impl.UsermanagementImpl$$FastClassBySpringCGLIB$$217d848.invoke(<generated>)
mts_java         | 	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
mts_java         | 	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771)
mts_java         | 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
mts_java         | 	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
mts_java         | 	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:366)
mts_java         | 	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:118)
mts_java         | 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
mts_java         | 	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
mts_java         | 	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:691)
mts_java         | 	at com.devonfw.application.mtsj.usermanagement.logic.impl.UsermanagementImpl$$EnhancerBySpringCGLIB$$90db37b9.findUserProfileByLogin(<generated>)
mts_java         | 	at com.devonfw.application.mtsj.general.common.impl.security.BaseUserDetailsService.retrievePrincipal(BaseUserDetailsService.java:164)
mts_java         | 	... 58 common frames omitted
```

### Steps to reproduce (bug) / Use Case of feature request (enhancement)

1. git clone https://github.com/devonfw/my-thai-star.git
2. cd my-thai-star
3. docker-compose up
4. Go to browser and register an user

### Comments/Hints:
No field for user name field in registration form.

### Affected version:

* OS: Linux (Release:	v19.04.4 Codename:	ArcoLinux 5.6.14-arch1-1) 2.11.1811.49 (Stable channel) (64-bit)
* Browser: Vivaldi
* Docker: Docker version 19.03.9-ce, build 9d988398e7
* Docker-compose: docker-compose version 1.24.1, build 4667896b
* My-thai-star commit: 5c07108a81b790a34a994cfe2691fa8e7ec0de76

**Comment by sujith-mn** [comment]
The below POST api already exists in the backend. May required to integrate with front end.
/services/rest/usermanagement/v1/user/

Front end may require username field also.
Password required bcrypt encryption before save.

**Comment by sujith-mn** [comment]
PR https://github.com/devonfw/my-thai-star/pull/979 created.

**Comment by sujith-mn** [comment]
Merged the changes.
https://github.com/devonfw/my-thai-star/pull/979
